name: Vercel CD

on:
  push:
    branches: [main, ci/cd-test]

  pull_request:
    branches: [main, ci/cd-test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

