name: Node Continuous Deployment

on:
  push:
    branches: [main, ci/cd-test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
