name: Vercel Continuous Deployment

on:
  push:
    branches: [main, ci/cd-test]

  pull_request:
    branches: [main, ci/cd-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

